version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: wallet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    container_name: valkey
    image: valkey/valkey:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data: