version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: wallet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    container_name: valkey
    image: valkey/valkey:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: dev
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.27.0
    ports:
      - "5046:80"
    volumes:
      - ${PWD}/.dev-env/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  postgres-data: